version: '3'

services:

  django:
    build: .
    command: /usr/local/bin/gunicorn techcruncherapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/technews/static
    expose:
      - "8000"
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 on the container
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - DJANGO_SETTINGS_MODULE=techcruncherapp.settings

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A techcruncherapp worker --loglevel=info
    #volumes:
      #- ./techcruncher:/app  # Mount the entire techcruncher folder
      #- ./techcruncher:/app/db
    depends_on:
      - redis
      - django
      - postgres
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A techcruncherapp beat --loglevel=info
    #volumes:
      #- ./techcruncher:/app/db  # Mount the entire techcruncher folder
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

volumes:
  static_volume:
  postgres_data:
