version: '3'

services:
  nginx:
    image: my-custom-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro  # Mount nginx.conf into Nginx container
    depends_on:
      - django  # Ensure Django service is started before Nginx

  django:
    build: .
    command: /usr/local/bin/gunicorn techcruncherapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/technews/static
    expose:
      - "8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A techcruncherapp worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  celery-beat:
    build: .
    command: celery -A techcruncherapp beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

volumes:
  static_volume:
