# Generated by Django 4.2.13 on 2024-05-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newspost',
            table='NewsPost',
        ),
    ]
