# Generated by Django 4.2.13 on 2024-05-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technews', '0002_alter_newspost_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newspost',
            table=None,
        ),
    ]
